enableGlobalCache: true

#nodeLinker: node-modules
nodeLinker: pnpm

packageExtensions:
  # https://github.com/wclr/ts-node-dev/pull/332#issuecomment-1471756427
  ts-node-dev@*:
    peerDependencies:
      "@types/node": "^16"